# Pandas – Core Concepts, Fundamentals, and Essential Methods

This notebook teaches pandas from scratch with detailed explanations, examples, and exercises.

## 1. What Is Pandas?
Pandas is the most widely used Python library for data analysis.

Key features:
- Provides `Series` (1D) and `DataFrame` (2D tabular data)
- Fast, optimized operations built on NumPy
- Easy data cleaning, transformation, joining, grouping, and slicing
- Supports CSV, Excel, SQL, JSON, Parquet, and more

In [1]:
import pandas as pd
import numpy as np
pd.__version__

'2.3.3'

## 2. Pandas Series (1D)
A **Series** is a 1D labeled array, similar to a NumPy array but with labels.

In [2]:

s = pd.Series([10, 20, 30, 40], index=["a", "b", "c", "d"])
s, s.index, s.values

(a    10
 b    20
 c    30
 d    40
 dtype: int64,
 Index(['a', 'b', 'c', 'd'], dtype='object'),
 array([10, 20, 30, 40]))

### Important Attributes:

In [3]:

print("Index:", s.index)
print("Values:", s.values)
print("Data type:", s.dtype)
print("Shape:", s.shape)

Index: Index(['a', 'b', 'c', 'd'], dtype='object')
Values: [10 20 30 40]
Data type: int64
Shape: (4,)

### Basic Operations

In [4]:

print(s + 10)
print(s * 2)
print(s[s > 20])

a    20
b    30
c    40
d    50
dtype: int64
a    20
b    40
c    60
d    80
dtype: int64
c    30
d    40
dtype: int64

## 3. DataFrame – The Core of Pandas
A **DataFrame** is a 2D, table-like structure with rows and columns.

In [5]:

data = {
    "name": ["Alice", "Bob", "Charlie", "David"],
    "age": [24, 30, 22, 28],
    "salary": [50000, 60000, 45000, 70000]
}
df = pd.DataFrame(data)
df

      name  age  salary
0    Alice   24   50000
1      Bob   30   60000
2  Charlie   22   45000
3    David   28   70000

### 3.1 DataFrame Attributes

In [6]:

df.head(), df.tail(), df.shape, df.columns, df.index, df.dtypes

(      name  age  salary
 0    Alice   24   50000
 1      Bob   30   60000
 2  Charlie   22   45000
 3    David   28   70000,
       name  age  salary
 0    Alice   24   50000
 1      Bob   30   60000
 2  Charlie   22   45000
 3    David   28   70000,
 (4, 3),
 Index(['name', 'age', 'salary'], dtype='object'),
 RangeIndex(start=0, stop=4, step=1),
 name      object
 age        int64
 salary     int64
 dtype: object)

## 4. Reading and Writing Data

In [7]:

# Example only (files not included in this environment)
# df = pd.read_csv("data.csv")
# df.to_excel("output.xlsx", index=False)

## 5. Selecting Data (The Most Important Skill)

### 5.1 Selecting Columns

In [8]:

df["name"]
df[["name", "salary"]]

      name  salary
0    Alice   50000
1      Bob   60000
2  Charlie   45000
3    David   70000

### 5.2 Selecting Rows

In [9]:

print(df.loc[0])        # by row label

print(df.iloc[0])       # by index position

df.iloc[1:3]     # slicing

name      Alice
age          24
salary    50000
Name: 0, dtype: object
name      Alice
age          24
salary    50000
Name: 0, dtype: object

      name  age  salary
1      Bob   30   60000
2  Charlie   22   45000

### 5.3 Boolean Filtering

In [10]:

df[df["age"] > 25]
df[(df["age"] > 25) & (df["salary"] > 55000)]

    name  age  salary
1    Bob   30   60000
3  David   28   70000

## 6. Sorting

In [11]:

df.sort_values("salary", ascending=False)

      name  age  salary
3    David   28   70000
1      Bob   30   60000
0    Alice   24   50000
2  Charlie   22   45000

## 7. Adding / Modifying Columns

In [12]:

df["salary_k"] = df["salary"] / 1000
df

      name  age  salary  salary_k
0    Alice   24   50000      50.0
1      Bob   30   60000      60.0
2  Charlie   22   45000      45.0
3    David   28   70000      70.0

## 8. Dropping Columns & Rows

In [ ]:

df.drop(columns=["salary_k"], inplace=False) # columns
df.drop(index=[2], inplace=False) # rows

    name  age  salary  salary_k
0  Alice   24   50000      50.0
1    Bob   30   60000      60.0
3  David   28   70000      70.0

## 9. Handling Missing Values (Important in Real Projects)

In [14]:

df2 = df.copy()
df2.loc[1, "salary"] = np.nan

df2.isna(), df2.fillna(0), df2.dropna()

(    name    age  salary  salary_k
 0  False  False   False     False
 1  False  False    True     False
 2  False  False   False     False
 3  False  False   False     False,
       name  age   salary  salary_k
 0    Alice   24  50000.0      50.0
 1      Bob   30      0.0      60.0
 2  Charlie   22  45000.0      45.0
 3    David   28  70000.0      70.0,
       name  age   salary  salary_k
 0    Alice   24  50000.0      50.0
 2  Charlie   22  45000.0      45.0
 3    David   28  70000.0      70.0)

## 10. GroupBy – Split, Apply, Combine

In [15]:

data = {
    "team": ["A", "A", "B", "B", "C"],
    "score": [10, 15, 10, 20, 30]
}
gdf = pd.DataFrame(data)
gdf.groupby("team")["score"].mean()

team
A    12.5
B    15.0
C    30.0
Name: score, dtype: float64

## 11. Aggregations

In [16]:

gdf.groupby("team").agg({
    "score": ["sum", "mean", "max", "count"]
})

     score
       sum  mean max count
team
A       25  12.5  15     2
B       30  15.0  20     2
C       30  30.0  30     1

## 12. Merging / Joining DataFrames

In [17]:

left = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["A", "B", "C"]
})
right = pd.DataFrame({
    "id": [1, 2, 4],
    "score": [90, 80, 70]
})
left.merge(right, on="id", how="inner")

   id name  score
0   1    A     90
1   2    B     80

## 13. Pivot Tables

In [18]:

pt = pd.DataFrame({
    "city": ["Hyd", "Hyd", "Delhi", "Delhi"],
    "year": [2023, 2024, 2023, 2024],
    "sales": [100, 150, 80, 130]
})
pt.pivot_table(values="sales", index="city", columns="year")

year    2023   2024
city
Delhi   80.0  130.0
Hyd    100.0  150.0

## 14. Apply / Lambda Functions (Powerful)

In [19]:

df["age_category"] = df["age"].apply(lambda x: "young" if x < 25 else "adult")
df

      name  age  salary  salary_k age_category
0    Alice   24   50000      50.0        young
1      Bob   30   60000      60.0        adult
2  Charlie   22   45000      45.0        young
3    David   28   70000      70.0        adult

## 15. Ranking

In [20]:

df["salary_rank"] = df["salary"].rank(ascending=False)
df

      name  age  salary  salary_k age_category  salary_rank
0    Alice   24   50000      50.0        young          3.0
1      Bob   30   60000      60.0        adult          2.0
2  Charlie   22   45000      45.0        young          4.0
3    David   28   70000      70.0        adult          1.0

## 16. Mini Exercises
Try before checking solutions.

1. Select all rows where salary > 55000
2. Create a new column `age*2`
3. Find average salary by age group
4. Sort by age descending
5. Count how many names start with each letter

### Example Solutions

In [21]:

print(df[df["salary"] > 55000])

df["age2"] = df["age"] * 2

print(df.groupby("age")["salary"].mean())

print(df.sort_values("age", ascending=False))

print(df["name"].str[0].value_counts())

    name  age  salary  salary_k age_category  salary_rank
1    Bob   30   60000      60.0        adult          2.0
3  David   28   70000      70.0        adult          1.0
age
22    45000.0
24    50000.0
28    70000.0
30    60000.0
Name: salary, dtype: float64
      name  age  salary  salary_k age_category  salary_rank  age2
1      Bob   30   60000      60.0        adult          2.0    60
3    David   28   70000      70.0        adult          1.0    56
0    Alice   24   50000      50.0        young          3.0    48
2  Charlie   22   45000      45.0        young          4.0    44
name
A    1
B    1
C    1
D    1
Name: count, dtype: int64